[project]
name = "medical-diagnosis-app"
version = "0.1.0"
description = "Medical Diagnosis Application"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "fastapi>=0.124.4",
    "lxml>=6.0.2",
    "mcp[cli]>=1.26.0",
    "openai==0.28",
    "python-dotenv>=1.0.1",
    "requests>=2.32.4",
    "uvicorn>=0.33.0",
]
